### ISSUE TITLE
Chrom suggestions: Lane, Nekofreak, Frisk, Updike, Annie, Botan and Pom Pom 

### ISSUE THREAD

**Issue by SPfnf** [xzh3r/xzh3r-utau#1]
just some chrom suggestions :)

**Comment by xzh3r** [comment]
I'll do them all except Botan and Updike. ExtendedCentral already has an Updike chromatic, and I have a Botan chromatic but it was given to me by Blantados and I can't share it. He should upload it eventually to his Github.
