### ISSUE TITLE
More chrom suggestions: KB, QT, Rosie, Snow, Nene (From friday night shootin), Lucian, Accerlant Hank, Peakek and MakoMelon

### ISSUE THREAD

**Issue by SPfnf** [xzh3r/xzh3r-utau#3]

**Comment by xzh3r** [comment]
Accelerant Hank already has a good soundfont on Gamebanana, ExtendedCentral has all of FNF Fever scales in the description of his Endurance cover, I don't know about Lucian because I can't find good samples, and ask Snow the Fox for the snow scale. I'll do the rest though.
